//! Mac Roman <-> UTF-8 conversion.
//!
//! Hotline's legacy text encoding is Mac Roman (the Classic Mac OS Roman
//! charset). The C code converts it through `g_convert(..., "MACINTOSH",
//! ...)` in `src/text_util.c`, which on a glibc system reaches glibc's
//! `iconv` "MACINTOSH" table. We replicate **that table byte-for-byte** so
//! the Rust path is a drop-in for the C path with no observable difference.
//!
//! The high-128 table below was generated by running each byte 0x80..=0xFF
//! through `iconv -f MACINTOSH -t UTF-32LE` on glibc and recording the
//! resulting codepoint. Two entries differ from the Unicode Consortium /
//! Python `mac_roman` table, and we deliberately follow glibc:
//!
//! - `0xC6` → U+0394 GREEK CAPITAL LETTER DELTA (not U+2206 INCREMENT).
//! - `0xF0` → U+E01E (a private-use codepoint, not U+F8FF Apple logo).
//!
//! Bytes 0x00..=0x7F are ASCII and map to themselves.

/// glibc `iconv` "MACINTOSH" mapping for bytes 0x80..=0xFF → Unicode scalar.
/// Index `i` corresponds to byte `0x80 + i`.
const MAC_ROMAN_HIGH: [u32; 128] = [
    0x00C4, 0x00C5, 0x00C7, 0x00C9, 0x00D1, 0x00D6, 0x00DC, 0x00E1, 0x00E0, 0x00E2, 0x00E4, 0x00E3,
    0x00E5, 0x00E7, 0x00E9, 0x00E8, 0x00EA, 0x00EB, 0x00ED, 0x00EC, 0x00EE, 0x00EF, 0x00F1, 0x00F3,
    0x00F2, 0x00F4, 0x00F6, 0x00F5, 0x00FA, 0x00F9, 0x00FB, 0x00FC, 0x2020, 0x00B0, 0x00A2, 0x00A3,
    0x00A7, 0x2022, 0x00B6, 0x00DF, 0x00AE, 0x00A9, 0x2122, 0x00B4, 0x00A8, 0x2260, 0x00C6, 0x00D8,
    0x221E, 0x00B1, 0x2264, 0x2265, 0x00A5, 0x00B5, 0x2202, 0x2211, 0x220F, 0x03C0, 0x222B, 0x00AA,
    0x00BA, 0x03A9, 0x00E6, 0x00F8, 0x00BF, 0x00A1, 0x00AC, 0x221A, 0x0192, 0x2248, 0x0394, 0x00AB,
    0x00BB, 0x2026, 0x00A0, 0x00C0, 0x00C3, 0x00D5, 0x0152, 0x0153, 0x2013, 0x2014, 0x201C, 0x201D,
    0x2018, 0x2019, 0x00F7, 0x25CA, 0x00FF, 0x0178, 0x2044, 0x20AC, 0x2039, 0x203A, 0xFB01, 0xFB02,
    0x2021, 0x00B7, 0x201A, 0x201E, 0x2030, 0x00C2, 0x00CA, 0x00C1, 0x00CB, 0x00C8, 0x00CD, 0x00CE,
    0x00CF, 0x00CC, 0x00D3, 0x00D4, 0xE01E, 0x00D2, 0x00DA, 0x00DB, 0x00D9, 0x0131, 0x02C6, 0x02DC,
    0x00AF, 0x02D8, 0x02D9, 0x02DA, 0x00B8, 0x02DD, 0x02DB, 0x02C7,
];

/// Convert wire bytes to a UTF-8 `String`, mirroring `gtkhx_text_to_utf8`.
///
/// Behaviour matches the C function exactly:
/// 1. If `bytes` is already valid UTF-8, it is returned verbatim (the C
///    code calls `g_utf8_validate` first and passes valid input through).
/// 2. Otherwise every byte is mapped through the Mac Roman table (ASCII
///    identity below 0x80, [`MAC_ROMAN_HIGH`] at and above). This always
///    succeeds, so there is no lossy `g_utf8_make_valid` fallback to model.
pub fn to_utf8(bytes: &[u8]) -> String {
    if let Ok(s) = std::str::from_utf8(bytes) {
        return s.to_owned();
    }
    let mut out = String::with_capacity(bytes.len());
    for &b in bytes {
        if b < 0x80 {
            out.push(b as char);
        } else {
            // Every index is a valid Unicode scalar by construction.
            let cp = MAC_ROMAN_HIGH[(b - 0x80) as usize];
            out.push(char::from_u32(cp).unwrap_or('\u{FFFD}'));
        }
    }
    out
}

/// Decode `bytes` (same rules as [`to_utf8`]) and write the resulting UTF-8
/// into `dst`, returning the number of bytes written. If the decoded output
/// is longer than `dst`, truncates at the last UTF-8 character boundary
/// that still fits — never writes a partial multi-byte sequence. No NUL
/// terminator is appended; the slice content is just the UTF-8 bytes.
///
/// This is the byte-oriented form a C caller wants (via the FFI shim) and
/// is also the right shape for a future Rust caller decoding into a
/// pre-sized scratch buffer. Sizing the destination at `bytes.len() * 3`
/// guarantees the result fits (Mac Roman → UTF-8 worst-case expansion is
/// 3×); a smaller destination causes truncation.
///
/// **No intermediate allocation.** Unlike [`to_utf8`] (which returns an
/// owned `String`), this writes straight into `dst`:
/// 1. Valid-UTF-8 fast path — verbatim copy from `bytes` to `dst`, with
///    boundary truncation when `dst` is smaller than `bytes`.
/// 2. Mac Roman path — per-byte table lookup, `char::encode_utf8` into a
///    4-byte stack scratch buffer, copy whole UTF-8 sequences into `dst`.
///    Loop breaks as soon as the next codepoint wouldn't fit, which
///    enforces the "no partial sequences" rule for free.
///
/// Hot path: this runs on every server chat / news / msg payload.
pub fn to_utf8_into(bytes: &[u8], dst: &mut [u8]) -> usize {
    if dst.is_empty() {
        return 0;
    }
    // Fast path: input is already valid UTF-8. Copy verbatim, truncating
    // at the last character boundary that fits.
    if std::str::from_utf8(bytes).is_ok() {
        let mut n = bytes.len().min(dst.len());
        if n < bytes.len() {
            while n > 0 && (bytes[n] & 0b1100_0000) == 0b1000_0000 {
                n -= 1;
            }
        }
        if n > 0 {
            dst[..n].copy_from_slice(&bytes[..n]);
        }
        return n;
    }
    // Mac Roman path: decode byte-by-byte directly into `dst`.
    let mut written = 0;
    let mut tmp = [0u8; 4];
    for &b in bytes {
        let seq: &[u8] = if b < 0x80 {
            tmp[0] = b;
            &tmp[..1]
        } else {
            let cp = MAC_ROMAN_HIGH[(b - 0x80) as usize];
            let ch = char::from_u32(cp).unwrap_or('\u{FFFD}');
            ch.encode_utf8(&mut tmp).as_bytes()
        };
        if written + seq.len() > dst.len() {
            // Next codepoint doesn't fit — stop, leaving `dst` ending at
            // the prior char boundary. (Don't continue with smaller
            // codepoints either: the caller wants a prefix, not a
            // gappy decode.)
            break;
        }
        dst[written..written + seq.len()].copy_from_slice(seq);
        written += seq.len();
    }
    written
}

/// Convert UTF-8 text to Mac Roman wire bytes, mirroring the legacy-mode
/// branch of `gtkhx_text_for_wire`. Characters outside the Mac Roman
/// repertoire are replaced with `?` (the same fallback the C code passes to
/// `g_convert_with_fallback`).
///
/// This does **not** perform the LF→CR body normalisation the C function
/// does for `is_body` fields; that stays a caller concern for now and moves
/// into the typed `build_*` serializers as `commands.c` is ported.
pub fn from_utf8(text: &str) -> Vec<u8> {
    let mut out = Vec::with_capacity(text.len());
    for ch in text.chars() {
        let cp = ch as u32;
        if cp < 0x80 {
            out.push(cp as u8);
        } else if let Some(idx) = MAC_ROMAN_HIGH.iter().position(|&c| c == cp) {
            out.push(0x80 + idx as u8);
        } else {
            out.push(b'?');
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ascii_is_identity() {
        assert_eq!(to_utf8(b"hello world"), "hello world");
        assert_eq!(from_utf8("hello world"), b"hello world");
    }

    #[test]
    fn valid_utf8_passes_through_untouched() {
        // A UTF-8 "é" (0xC3 0xA9) is valid UTF-8 and must NOT be reinterpreted
        // as two Mac Roman bytes (which would be "√©").
        assert_eq!(to_utf8(&[0xC3, 0xA9]), "é");
    }

    #[test]
    fn mac_roman_high_bytes_decode() {
        // 0x8E is Mac Roman 'é'; as a lone high byte it isn't valid UTF-8,
        // so the Mac Roman branch runs.
        assert_eq!(to_utf8(&[0x8E]), "é");
        // 0xA5 is BULLET, 0xA9 is TRADE MARK SIGN.
        assert_eq!(to_utf8(&[0xA5]), "•");
        assert_eq!(to_utf8(&[0xAA]), "™");
    }

    #[test]
    fn glibc_specific_entries() {
        // 0xC6 → Δ (glibc), not ∆. 0xDB → € (glibc euro update).
        assert_eq!(to_utf8(&[0xC6]), "Δ");
        assert_eq!(to_utf8(&[0xDB]), "€");
    }

    #[test]
    fn roundtrip_representable_chars() {
        let s = "café ™ • Ø";
        let wire = from_utf8(s);
        assert_eq!(to_utf8(&wire), s);
    }

    #[test]
    fn unrepresentable_becomes_question_mark() {
        // An emoji has no Mac Roman codepoint.
        assert_eq!(from_utf8("hi 😀"), b"hi ?");
    }

    // ---- to_utf8_into: byte-buffer form ----

    #[test]
    fn into_empty_dst_writes_nothing() {
        let mut dst = [];
        assert_eq!(to_utf8_into(b"hello", &mut dst), 0);
    }

    #[test]
    fn into_ascii_copies() {
        let mut dst = [0u8; 32];
        let n = to_utf8_into(b"hello", &mut dst);
        assert_eq!(n, 5);
        assert_eq!(&dst[..n], b"hello");
    }

    #[test]
    fn into_mac_roman_decodes() {
        // 0x8E is Mac Roman 'é' → UTF-8 0xC3 0xA9 (2 bytes).
        let mut dst = [0u8; 32];
        let n = to_utf8_into(&[0x8E], &mut dst);
        assert_eq!(n, 2);
        assert_eq!(&dst[..n], b"\xC3\xA9");
    }

    #[test]
    fn into_valid_utf8_passes_through() {
        let mut dst = [0u8; 32];
        let n = to_utf8_into(b"\xC3\xA9", &mut dst);
        assert_eq!(n, 2);
        assert_eq!(&dst[..n], b"\xC3\xA9");
    }

    #[test]
    fn into_truncates_at_utf8_char_boundary() {
        // Mac Roman 0xAA → "™" → UTF-8 0xE2 0x84 0xA2 (3 bytes). dst of 2
        // would slice the 3-byte sequence; the function must back up and
        // write nothing rather than emit a partial sequence.
        let mut dst = [0u8; 2];
        assert_eq!(to_utf8_into(&[0xAA], &mut dst), 0);
        // dst of 3 fits exactly.
        let mut dst = [0u8; 3];
        let n = to_utf8_into(&[0xAA], &mut dst);
        assert_eq!(n, 3);
        assert_eq!(&dst[..n], b"\xE2\x84\xA2");
    }

    #[test]
    fn into_truncates_mid_string_at_boundary() {
        // "a" + Mac Roman 0xAA "™" + "b" → "a" + 3 + "b" = 5 bytes total.
        // dst of 4 fits "a" + "™"; "b" doesn't fit and is dropped.
        let mut dst = [0u8; 4];
        let n = to_utf8_into(&[b'a', 0xAA, b'b'], &mut dst);
        assert_eq!(n, 4);
        assert_eq!(&dst[..n], b"a\xE2\x84\xA2");
        // dst of 3: "a" + first 2 bytes of "™" — must drop the multi-byte
        // char entirely, leaving just "a".
        let mut dst = [0u8; 3];
        let n = to_utf8_into(&[b'a', 0xAA, b'b'], &mut dst);
        assert_eq!(n, 1);
        assert_eq!(&dst[..n], b"a");
    }

    #[test]
    fn into_empty_input_writes_nothing() {
        let mut dst = [0u8; 16];
        assert_eq!(to_utf8_into(b"", &mut dst), 0);
    }
}
